version: "2"

services:
  consul1: 
    image: "consul"
    container_name: "consul1"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      # environment:
      #   - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      #   - "CONSUL_BIND_INTERFACE=eth0"
      #   - "CONSUL_HTTP_ADDR=0.0.0.0"
    hostname: "consul1"
    ports:
      - "8301:8301"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    # command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetPrivateIP }}'"
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetInterfaceIP \"eth0\" }}'"
  consul2: 
    image: "consul"
    container_name: "consul2"
    hostname: "consul2"
    ports:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -retry-join consul1"
    depends_on:
      - consul1
  consul3: 
    image: "consul"
    container_name: "consul3"
    hostname: "consul3"
    ports:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -retry-join consul1"
    depends_on:
      - consul1
  # Not working
  server:
    build: "./server"
    container_name: "node-consul-server"
    links:
      - consul1
    command: "npm start"
    volumes: 
      - "./server:/src"
    environment:
      - ADDRESS=consul1
